# This is a basic workflow to help you get started with Actions

name: NPM Build and Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          
      - name: Install
        run: npm install

      # Runs a single command using the runners shell
      - name: Build
        run: npm run build:ci

      - uses: JS-DevTools/npm-publish@v1
        name: Publish
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
